#+STARTUP: overview 
* Romantic Era 
** John Keats, 1795-1821 
- British Romantic poet. One of the main figures of the second
  generation of Romantic poets (along with Lord Byron & Percy Bysshe
  Shelley). Delivering strong emotional and sensual accentuation
  through natural imagery.
*** La Belle Dame sans Merci 
- Content
#+BEGIN_SRC text
  O what can ail thee, Knight at arms, 
  Alone and palely loitering? 
  The sedge has withered from the Lake 
  And no birds sing! 

  O what can ail thee, Knight at arms, 
  So haggard and so woebegone? 
  The squirrel's granary is full 
  And the harvest's done. 

  I see a lily on thy brow 
  With anguish moise and fever dew,
  And on thy cheeks a fading rose 
  Fast withereth too. 

  I met a Lady in the Meads, 
  Full beautiful, a faery's child, 
  Her hair was long, her foot was light 
  And her eyes were wild. 

  I made a Garland for her 
  And bracelets too, and fragrant zone; 
  She looked at me as she did love 
  And made sweet moan. 

  I set her on my pacing steed 
  And nothing else saw all day long, 
  For sidelong would she bend and sing 
  A faery's song. 

  She found me roots of relish sweet, 
  And honey wild, and manna dew, 
  And sure in language strange she said 
  'I love thee true.'

  She took me to her elfin grot 
  And there she wept and sighed full sore, 
  And there I shut her wild wild eyes 
  With kisses four. 

  And there she lulled me asleep. 
  And there I dreamed, Ah woe betide! 
  The latest dream I ever dreamt 
  On the cold hill side. 

  I saw pale Kings, and Princes too, 
  Pale warriors, death-pale were they all; 
  They cried, 'La belle dame sans merci 
  Thee hath in thrall!' 

  I saw their starved lips in the gloam 
  With horrid warning gaped wide, 
  And i awoke, and found me here 
  On the cold hill's side. 

  And this is why I sojourn here, 
  Alone and palely loitering. 
  Though the sedge is withered from the Lake 
  And no birds sing. 
#+END_SRC
- Analysis 
#+BEGIN_SRC text
  ,* Intro 
  - This is a ballad borrowing the title of the 15th century La Belle Dame
  sans Mercy by Alain Chartier but not the content. It shows
  Keats'poetic preoccupation with love and death.
  ,* Structure 
  - Twelve stanzas of 4 lines each in a ABCB rhyme scheme. 
  - Each stanza consists of 3 iambic tetrameter lines followed by a
    final dimetric line. It gives the ballad a deliberate and slow
    movement pleasing to the ear. 
  ,* Style & techniques 
  - A number of stylistic characters of a ballad, including the
    simplicity of language,repetition and absence of details.
  - The wintry, dire landscape builds the settings well for the
    ill-fated knight's love tragedy.
#+END_SRC
*** Ode to a Nightingale 
- Content 
#+BEGIN_SRC text
  My heart aches, and a drowsy numbness pains 
  My sense, as though of hemlock I had drunk, 
  Or emptied some dull opiate to the drains 
  One minute past, and Lethe-wards had sunk 
  ’Tis not through envy of thy happy lot, 
  But being too happy in thine happiness, - 
  That thou, light-winged Dryad of the trees, 
  In some melodious plot 
  Of beechen green and shadows numberless, 
  Singest of summer in full-throated ease. 
  O, for a draught of vintage! that hath been 
  Cool’d a long age in the deep-delved earth, 
  Tasting of Flora and the country green, 
  Dance, and Provencal song, and sunburnt mirth! 
  O for a beaker full of the warm South, 
  Full of the true, the blushful Hippocrene, 
  With beaded bubbles winking at the brim, 
  And purple-stained mouth; 
  That I might drink, and leave the world unseen, 
  And with thee fade away into the forest dim: 

  Fade far away, dissolve, and quite forget 
  What thou among the leaves hast never known, 
  The weariness, the fever, and the fret 
  Here, where men sit and hear each other groan; 
  Where palsy shakes a few, sad, last gray hairs, 
  Where youth grows pale, and spectre-thin, and dies; 
  Where but to think is to be full of sorrow, 
  And leaden-eyed despairs, 
  Where Beauty cannot keep her lustrous eyes, 
  Or new Love pine at them beyond to-morrow. 

  Away! away! for I will fly to thee, 
  Not charioted by Bacchus and his pards, 
  But on the viewless wings of Poesy, 
  Though the dull brain perplexes and retards: 
  Already with thee! tender is the night, 
  And haply the Queen-Moon is on her throne, 
  Cluster’d around by all her starry Fays; 
  But here there is no light, 
  Save what from heaven is with the breezes blown 
  Though verdurous glooms and winding mossy ways. 

  I cannot see what flowers are at my feet, 
  Nor what soft incense hangs upon the boughs, 
  But, in embalmed darkness, guess each sweet 
  Wherewith the seasonable month endows 
  The grass, the thicket, and the fruit-tree wild; 
  White hawthorn, and the pastoral eglantine; 
  Fast fading violets cover’d up in leaves; 
  And mid-May’s eldest child, 
  The coming musk-rose, full of dewy wine, 
  The murmurous haunt of flies on summer eves. 

  Darkling I listen; and, for many a time 
  I have been half in love with easeful Death, 
  Call’d him soft names in many a mused rhyme, 
  To take into the air my quiet breath; 
  Now more than ever seems it rich to die, 
  To cease upon the midnight with no pain, 
  While thou art pouring forth thy soul abroad 
  In such an ecstasy! 
  Still wouldst thou sing, and I have ears in vain - 
  To thy high requiem become a sod. 

  Thou wast not born for death, immortal bird! 
  No hungry generations tread thee down; 
  The voice I hear this passing night was heard 
  In ancient days by emperor and clown: 
  Perhaps the self-same song that found a path 
  Through the sad heart of Ruth, when, sick for home, 
  She stood in tears amid the alien corn; 
  The same that oft-time hath 
  Charm’d magic casements, opening on the foam 
  Of perilous seas, in faery lands forlorn. 

  Forlorn! the very word is like a bell 
  To toll me back from thee to my sole self! 
  Adieu! the fancy cannot cheat so well 
  As she is fam’d to do, deceiving elf. 
  Adieu! adieu! thy plaintive anthem fades 
  Past the near meadows, over the still stream, 
  Up the hill-side; and now ’tis buried deep 
  In the next valley-glades: 
  Was it a vision, or a waking dream? 
  Fled is that music: - Do I wake or sleep?
#+END_SRC
- Analysis 
#+BEGIN_SRC text 
  ,* Vowel forms - short & long 
  ,* Sound patterns 
  ,** double/triple caesuras 
  ,** A complex reliance on assonance 
  ,** Less Latin-based words/syntax that reduce the length of words 
  ,** Words beginning with consonants (esp. ‘b’, ‘p’, ‘v’) used syzygically to create a musical tone 
#+END_SRC
*** Sleep and Poetry 
- Content 
#+BEGIN_SRC text
  What is more gentle than a wind in summer? 
  What is more soothing than the pretty hummer 
  That stays one moment in an open flower, 
  And buzzes cheerily from bower to bower? 
  What is more tranquil than a musk-rose blowing 
  In a green island, far from all men’s knowing? 
  More healthful than the leafiness of dales? 
  More secret than a nest of nightingales? 
  More serene than Cordelia’s countenance? 
  More full of visions than a high romance? 
  What, but thee sleep? Soft closer of our eyes! 
  Low murmurer of tender lullabies 
  Light hoverer around our happy pillows! 
  Wreather of poppy buds, and weeping willows! 
  Silent entangler of a beauty’s tresses! 
  Most happy listener! when the morning blesses 
  Thee for enlivening all the cheerful eyes 
  That glance so brightly at the new sun-rise.
#+END_SRC
- Analysis 
#+BEGIN_SRC text
  Though featuring the simplistic form of rhyming couplets, Keats’
  poetry expresses emotions and stimulating thoughts more inwards by
  romantic standards
#+END_SRC
*** On First Looking into Chapman's Homer 
- Content
#+BEGIN_SRC text
  Much have I travell’d in the realms of gold, 
  And many goodly states and kingdoms seen; 
  Round many western islands have I seen 
  Which bards in fealty to Apollo told 
  That deep-browed Homer ruled as his demesne; 
  Yet did I never breathe its pure serene 
  Till I heard Chapman speak out load and bold: 
  Then felt I like some watcher of the skies 
  When a new planet swims into his ken; 
  Or like stout Cortez when with eagle eyes 
  He start’d at the Pacific - and all his men 
  Look’d at each other with a wild surmise - 
  Silent, upon a peak in Darien.
#+END_SRC
- Analysis 
#+BEGIN_SRC text
  One of Keats’ most quoted classics as a demonstration of the lasting
  provocative power of great works of art among an audience of later
  generations
#+END_SRC
* Contemporary America 
** Robert Frost, 1874-1963 
*** A Late Walk 
#+BEGIN_SRC text
  When I go up through the mowing field, 
  The headless aftermath, 
  Smooth-laid like thatch with the heavy dew, 
  Half closes the garden path. 

  And when I come to the garden ground, 
  The whir of sober birds, 
  Up from the tangle of withered weeds, 
  Is sadder than any words. 

  A tree beside the wall stands bare, 
  But a leaf that lingered brown, 
  Disturbed, I doubt not, by my thought, 
  Comes softly rattling down. 

  I end not far from my going forth 
  By picking the faded blue 
  Of the last remaining aster flower 
  To carry again to you.
#+END_SRC
** Denise Levertov, 1923-1997 
- American peot. Born in southeast of England to a Russian father who
  was a Hasidic Jew. She struggled with her identity among Jewish,
  German, Welsh and English, and considered herself belonging to none
  of them fully. This gave her a brand new perspective and a passion
  for humanitarian politics. 
- Showing great promise as an young talent in
  writing, her poems received encouragement from T.S. Elliot at the
  age of 12. Her first poem was published when she was 17 and her book
  6 years later. 
- She stemmed from traditional forms and language and later embraced
  an American style, inspired by the Black Mountain poets and most
  importantly William Carlos Williams. Politics and war are major
  themes in her poetry, along with suffering. She also wrote a great
  amount of religious-themed poems. 
- Her first book - The Double Image; Her first American book of
  poetry that shows her transition of style - Here and Now; Her peom -
  With Eyes at the Back of Our Heads - established her reputation. 
*** The Secret 
#+BEGIN_SRC text
  Two girls discover
  the secret of life
  in a sudden line of
  peotry.

  I who don't know the
  secret wrote
  the line. They
  told me

  (through a third person)
  they had found it
  but not what it was
  not even

  what line it was. No doubt
  by now, more than a week
  later, they have forgotten
  the secret,

  the line, the name of
  the poem, I love them
  for finding what
  I can't find,

  and for loving me
  for the line I wrote,
  and for forgetting it
  so that

  a thousand times, till death
  finds them, they may
  discover it again, in other
  lines,

  in other
  happenings. And for
  wanting to know it,
  for

  assuming there is
  such a secret, yes,
  for that
  most of all. 
#+END_SRC
